[mypy]
python_version = 3.11
ignore_missing_imports = True
no_strict_optional = True
exclude = alembic/
warn_unused_ignores = False
disable_error_code =
    arg-type,
    assignment,
    attr-defined,
    call-arg,
    call-overload,
    import-untyped,
    index,
    list-item,
    no-redef,
    operator,
    return-value,
    union-attr

[mypy-playwright.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-bcrypt.*]
ignore_missing_imports = True

[mypy-reportlab.*]
ignore_missing_imports = True
