ACTUAR_SELECTORS = {
    "login_username": 'input[type="email"], input[name="email"], input[name="username"], input[name="user"], #userName, input[type="text"]',
    "login_password": 'input[name="password"], input[type="password"]',
    "login_submit": 'button.ladda-button.actuar, button[type="submit"]:has-text("FAZER LOGIN"), button[type="submit"]:has-text("Entrar"), input[type="submit"]',
    "member_search_input": 'input[name="search"], input[name="member_search"], input[placeholder*="Aluno" i], input[placeholder*="Buscar" i], input[placeholder*="Pesquisar" i], input[type="search"]',
    "member_search_submit": 'button:has-text("Buscar"), button:has-text("Pesquisar"), button:has-text("Lupa"), button[type="submit"]',
    "member_result_row": 'div[id^="card-"], [data-testid="member-result"], table tbody tr, .member-row',
    "member_result_name": '[data-testid="member-name"], .member-name, td:first-child',
    "member_result_birthdate": '[data-testid="member-birthdate"], .member-birthdate, td:nth-child(2)',
    "member_result_document": '[data-testid="member-document"], .member-document, td:nth-child(3)',
    "member_profile_link": 'a[href*="#/avaliacoes/perfil-avaliado/"], a:has-text("Perfil"), button:has-text("Perfil"), a:has-text("Abrir"), button:has-text("Abrir")',
    "member_result_new_assessment_button": 'div.nova-avaliacao a.btn-success[href*="#/avaliacoes/avaliacao/"], a.btn-success[href*="#/avaliacoes/avaliacao/"]:has-text("Nova avaliação"), a.btn-success[href*="#/avaliacoes/avaliacao/"]:has-text("Nova avaliacao"), a:has-text("Nova avaliação"), button:has-text("Nova avaliação"), a:has-text("Nova avaliacao"), button:has-text("Nova avaliacao")',
    "physical_assessment_entry": 'a:has-text("Avaliação física"), button:has-text("Avaliação física"), a:has-text("Avaliacao fisica"), button:has-text("Avaliacao fisica"), a:has-text("Avaliações físicas"), button:has-text("Avaliações físicas"), a:has-text("Avaliacoes fisicas"), button:has-text("Avaliacoes fisicas"), a[href*="#/avaliacoes"]',
    "new_assessment_button": 'div.nova-avaliacao a.btn-success[href*="#/avaliacoes/avaliacao/"], a.btn-success[href*="#/avaliacoes/avaliacao/"], a:has-text("Nova avaliação"), button:has-text("Nova avaliação"), a:has-text("Nova avaliacao"), button:has-text("Nova avaliacao"), a:has-text("Nova avaliação física"), button:has-text("Nova avaliação física"), a:has-text("Nova avaliacao fisica"), button:has-text("Nova avaliacao fisica")',
    "assessment_history_table": '.table-responsive table.table-striped, .table-responsive table, table.table-striped',
    "body_composition_tab": 'app-menu a.bg-primary, a:has-text("Composição corporal e perimetria"), button:has-text("Composição corporal e perimetria"), div:has-text("Composição corporal e perimetria"), a:has-text("Composicao corporal e perimetria"), button:has-text("Composicao corporal e perimetria"), div:has-text("Composicao corporal e perimetria"), [role="tab"]:has-text("Composição corporal e perimetria"), [role="tab"]:has-text("Composicao corporal e perimetria"), [role="button"]:has-text("Composição corporal e perimetria"), [role="button"]:has-text("Composicao corporal e perimetria")',
    "anamnesis_tab": 'a:has-text("Anamnese"), button:has-text("Anamnese"), [role="tab"]:has-text("Anamnese")',
    "protocol_select": 'select[name="protocoloComposicaoCorporalId"], select[name="ProtocoloComposicaoCorporalId"], select[name="BodyCompositionProtocolId"], select[id*="protocoloComposicaoCorporalId" i], select[id*="BodyCompositionProtocolId" i]',
    "weight_input": 'input#massa, input[name="massa"], input[name="Massa"], input[name="WeightKg"], input[id="massa"], input[id*="WeightKg" i]',
    "height_input": 'input#estatura, input[name="estatura"], input[name="Estatura"], input[name="HeightCm"], input[id="estatura"], input[id*="HeightCm" i]',
    "mass_total_current_input": 'input[name="MassaTotalAtual"], input[id*="MassaTotalAtual" i]',
    "mass_total_target_input": 'input[name="MassaTotalAlvo"], input[name="TargetWeightKg"], input[id*="MassaTotalAlvo" i], input[id*="TargetWeightKg" i]',
    "body_fat_percent_input": 'input[name="PercentualGorduraAtual"], input[name="CurrentFatPercentage"], input[id*="PercentualGorduraAtual" i], input[id*="CurrentFatPercentage" i]',
    "muscle_mass_input": 'input[name="MassaMuscularAtual"], input[name="CurrentMuscleMass"], input[id*="MassaMuscularAtual" i], input[id*="CurrentMuscleMass" i]',
    "fat_mass_input": 'input[name="MassaGorduraAtual"], input[name="CurrentFatMass"], input[name="FatMassKg"], input[id*="MassaGorduraAtual" i], input[id*="CurrentFatMass" i], input[id*="FatMassKg" i]',
    "lean_mass_input": 'input[name="MassaMagraAtual"], input[name="CurrentLeanMass"], input[name="LeanMassKg"], input[name="FatFreeMassKg"], input[id*="MassaMagraAtual" i], input[id*="CurrentLeanMass" i], input[id*="LeanMassKg" i], input[id*="FatFreeMassKg" i]',
    "bmi_input": 'input[name="imc"], input[name="IMC"], input[name="Bmi"], input[name="BMI"], input[id*="imc" i], input[id*="bmi" i]',
    "body_water_percent_input": 'input[name="PercentualAguaAtual"], input[name="BodyWaterPercent"], input[name="CurrentWaterPercentage"], input[id*="PercentualAguaAtual" i], input[id*="BodyWaterPercent" i], input[id*="CurrentWaterPercentage" i]',
    "bmr_input": 'input[name="TaxaMetabolicaBasal"], input[name="BasalMetabolicRate"], input[name="BmrKcal"], input[id*="TaxaMetabolicaBasal" i], input[id*="BasalMetabolicRate" i], input[id*="BmrKcal" i]',
    "total_energy_input": 'input[name="GastoEnergetico"], input[name="GastoEnergeticoTotal"], input[name="TotalEnergyKcal"], input[name="TotalEnergyExpenditure"], input[id*="GastoEnergetico" i], input[id*="GastoEnergeticoTotal" i], input[id*="TotalEnergyKcal" i], input[id*="TotalEnergyExpenditure" i]',
    "assessment_form": 'form, [data-testid="assessment-form"], [data-testid="body-composition-form"]',
    "update_button": 'button.btn-primary:has-text("Atualizar"), button:has-text("Atualizar")',
    "save_button": 'button:has-text("Salvar"), button[type="submit"], input[type="submit"]',
}

ACTUAR_FIELD_SELECTORS = {
    "evaluation_date": 'input[name="evaluation_date"], input[name="date"], input[type="date"]',
    "weight": ACTUAR_SELECTORS["weight_input"],
    "height_cm": ACTUAR_SELECTORS["height_input"],
    "target_weight_kg": ACTUAR_SELECTORS["mass_total_target_input"],
    "body_fat_percent": ACTUAR_SELECTORS["body_fat_percent_input"],
    "fat_mass_kg": ACTUAR_SELECTORS["fat_mass_input"],
    "lean_mass_kg": ACTUAR_SELECTORS["lean_mass_input"],
    "muscle_mass_kg": ACTUAR_SELECTORS["muscle_mass_input"],
    "bmi": ACTUAR_SELECTORS["bmi_input"],
    "body_water_percent": ACTUAR_SELECTORS["body_water_percent_input"],
    "bmr_kcal": ACTUAR_SELECTORS["bmr_input"],
    "total_energy_kcal": ACTUAR_SELECTORS["total_energy_input"],
    "anamnesis_summary": 'textarea[name="historicoPessoal"], textarea[name="notes"], textarea',
    "notes": 'textarea[name="notes"], textarea[name="historicoPessoal"], textarea',
}
